### ISSUE TITLE
NPM error on NPM install

### ISSUE THREAD

**Issue by sebs** [WPP-Public/akqa-nz-async-load#1]
I tried to check out the sources and do a NPM install 

```
npm http 404 https://registry.npmjs.org/buster
npm ERR! registry error parsing json
npm http 404 https://registry.npmjs.org/grunt-plugin-buster
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token H
npm ERR! Host not found: registry.npmjs.org
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:226:23)
npm ERR!     at Request.init.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:120:22)
npm ERR!     at Request.EventEmitter.emit (events.js:99:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:648:16)
npm ERR!     at Request.EventEmitter.emit (events.js:126:20)
npm ERR!     at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/usr/local/lib/node_modules/npm/node_modules/request/main.js:610:14)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:126:20)
npm ERR!     at IncomingMessage._emitEnd (http.js:366:10)
npm ERR!     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Admin/projects/async-load
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! type unexpected_token
npm http 404 https://registry.npmjs.org/grunt-contrib-jshint
npm ERR! registry error parsing json
npm http 404 https://registry.npmjs.org/grunt-contrib-uglify
npm ERR! registry error parsing json
npm http 404 https://registry.npmjs.org/grunt
npm ERR! registry error parsing json
```

Could be a tem issue, but I dont think so. Might be a result of the missing Version numbers in package JSOn.

**Comment by pieterv** [comment]
I have updated the `package.json` file to include specific version numbers.

`npm install` is working for me, even before the latest commit. But having a look through your error log it looks like you are getting http 404 errors which could be causing the problems. Maybe have another go with the latest commits and see if that works?

**Comment by sebs** [comment]
Hmm, all my other packages seem to install fine, I have several very simillar ones running. 
I will retest soon and keep you posted. looks like this one will be part of our stack, so we are very interested in CI and Test etc

**Comment by pieterv** [comment]
Im going to close this issue, let me know if you are still experiencing this problem and i can reopen it.

**Comment by sebs** [comment]
I will re-check, sorry for non-feedback

**Comment by sebs** [comment]
Works like a charm
